FROM node:12-alpine

WORKDIR /home/node/sff-front

ENV PATH /home/node/sff-front/node_modules/.bin:$PATH

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm install
RUN npm install react-scripts -g

COPY . .

EXPOSE 3000

CMD ["npm", "start"]