FROM node:12-alpine

WORKDIR /home/node/sff-front

ENV PATH /home/node/sff-front/node_modules/.bin:$PATH

COPY package.json package.json
COPY yarn.lock yarn.lock

RUN yarn install --silent
RUN yarn global add react-scripts --silent

COPY . .

EXPOSE 3000

CMD ["yarn", "start"]